__model__ = "AnIML"

[__sources__]
LibName = "URL to the library"

[AnIML]
id = "Enter target"
version = "Enter target"

[sample_set]
id = "Enter target"

[experiment_step_set]
id = "Enter target"

[audit_trail_entry_set]
id = "Enter target"

["sample_set.sample"]
id = "Enter target"
name = "Enter target"
sample_id = "Enter target"
barcode = "Enter target"
comment = "Enter target"
derived = "Enter target"
container_type = "Enter target"
container_id = "Enter target"
location_in_container = "Enter target"
source_data_location = "Enter target"

["experiment_step_set.experiment_step"]
id = "Enter target"
name = "Enter target"
experiment_step_id = "Enter target"
template_used = "Enter target"
comment = "Enter target"
source_data_location = "Enter target"

["experiment_step_set.template"]
id = "Enter target"
name = "Enter target"
template_id = "Enter target"
source_data_location = "Enter target"

["audit_trail_entry_set.audit_trail_entry"]
id = "Enter target"
timestamp = "Enter target"
action = "Enter target"
reason = "Enter target"
comment = "Enter target"
reference = "Enter target"

["sample_set.sample.tag_set"]
id = "Enter target"

["sample_set.sample.category"]
id = "Enter target"
name = "Enter target"
category = "Enter target"

["experiment_step_set.experiment_step.tag_set"]
id = "Enter target"

["experiment_step_set.experiment_step.technique"]
id = "Enter target"
name = "Enter target"
uri = "Enter target"
sha256 = "Enter target"

["experiment_step_set.experiment_step.infrastructure"]
id = "Enter target"
timestamp = "Enter target"

["experiment_step_set.experiment_step.method"]
id = "Enter target"
name = "Enter target"

["experiment_step_set.experiment_step.result"]
id = "Enter target"
name = "Enter target"

["experiment_step_set.template.tag_set"]
id = "Enter target"

["experiment_step_set.template.technique"]
id = "Enter target"
name = "Enter target"
uri = "Enter target"
sha256 = "Enter target"

["experiment_step_set.template.infrastructure"]
id = "Enter target"
timestamp = "Enter target"

["experiment_step_set.template.method"]
id = "Enter target"
name = "Enter target"

["experiment_step_set.template.result"]
id = "Enter target"
name = "Enter target"

["audit_trail_entry_set.audit_trail_entry.author"]
id = "Enter target"
user_type = "Enter target"
name = "Enter target"
affiliation = "Enter target"
role = "Enter target"
email = "Enter target"
phone = "Enter target"
location = "Enter target"

["audit_trail_entry_set.audit_trail_entry.software"]
id = "Enter target"
name = "Enter target"
manufacturer = "Enter target"
version = "Enter target"
operating_system = "Enter target"

["audit_trail_entry_set.audit_trail_entry.diff"]
id = "Enter target"
scope = "Enter target"
changed_item = "Enter target"
old_value = "Enter target"
new_value = "Enter target"

["sample_set.sample.tag_set.tag"]
id = "Enter target"
name = "Enter target"
value = "Enter target"

["experiment_step_set.experiment_step.tag_set.tag"]
id = "Enter target"
name = "Enter target"
value = "Enter target"

["experiment_step_set.experiment_step.technique.extension"]
id = "Enter target"
uri = "Enter target"
name = "Enter target"
sha256 = "Enter target"

["experiment_step_set.experiment_step.infrastructure.sample_reference_set"]
id = "Enter target"

["experiment_step_set.experiment_step.infrastructure.parent_data_point_reference_set"]
id = "Enter target"

["experiment_step_set.experiment_step.infrastructure.experiment_data_reference_set"]
id = "Enter target"

["experiment_step_set.experiment_step.method.author"]
id = "Enter target"
user_type = "Enter target"
name = "Enter target"
affiliation = "Enter target"
role = "Enter target"
email = "Enter target"
phone = "Enter target"
location = "Enter target"

["experiment_step_set.experiment_step.method.device"]
id = "Enter target"
name = "Enter target"
device_identifier = "Enter target"
manufacturer = "Enter target"
firmware_version = "Enter target"
serial_number = "Enter target"

["experiment_step_set.experiment_step.method.software"]
id = "Enter target"
name = "Enter target"
manufacturer = "Enter target"
version = "Enter target"
operating_system = "Enter target"

["experiment_step_set.experiment_step.method.category"]
id = "Enter target"
name = "Enter target"
category = "Enter target"

["experiment_step_set.template.tag_set.tag"]
id = "Enter target"
name = "Enter target"
value = "Enter target"

["experiment_step_set.template.technique.extension"]
id = "Enter target"
uri = "Enter target"
name = "Enter target"
sha256 = "Enter target"

["experiment_step_set.template.infrastructure.sample_reference_set"]
id = "Enter target"

["experiment_step_set.template.infrastructure.parent_data_point_reference_set"]
id = "Enter target"

["experiment_step_set.template.infrastructure.experiment_data_reference_set"]
id = "Enter target"

["experiment_step_set.template.method.author"]
id = "Enter target"
user_type = "Enter target"
name = "Enter target"
affiliation = "Enter target"
role = "Enter target"
email = "Enter target"
phone = "Enter target"
location = "Enter target"

["experiment_step_set.template.method.device"]
id = "Enter target"
name = "Enter target"
device_identifier = "Enter target"
manufacturer = "Enter target"
firmware_version = "Enter target"
serial_number = "Enter target"

["experiment_step_set.template.method.software"]
id = "Enter target"
name = "Enter target"
manufacturer = "Enter target"
version = "Enter target"
operating_system = "Enter target"

["experiment_step_set.template.method.category"]
id = "Enter target"
name = "Enter target"
category = "Enter target"

["sample_set.sample.category.parameter"]
id = "Enter target"
name = "Enter target"
parameter_type = "Enter target"
value = "Enter target"

["sample_set.sample.category.series_set"]
id = "Enter target"
name = "Enter target"
length = "Enter target"

["experiment_step_set.experiment_step.infrastructure.sample_reference_set.sample_reference"]
id = "Enter target"
sample_id = "Enter target"
role = "Enter target"
sample_purpose = "Enter target"

["experiment_step_set.experiment_step.infrastructure.sample_reference_set.sample_inheritance"]
id = "Enter target"
role = "Enter target"
sample_purpose = "Enter target"

["experiment_step_set.experiment_step.infrastructure.parent_data_point_reference_set.parent_data_point_reference"]
id = "Enter target"
series_id = "Enter target"

["experiment_step_set.experiment_step.infrastructure.experiment_data_reference_set.experiment_data_reference"]
id = "Enter target"
role = "Enter target"
data_purpose = "Enter target"
experiment_step_id = "Enter target"

["experiment_step_set.experiment_step.infrastructure.experiment_data_reference_set.experiment_data_bulk_reference"]
id = "Enter target"
role = "Enter target"
data_purpose = "Enter target"
experiment_step_id_prefix = "Enter target"

["experiment_step_set.experiment_step.result.series_set"]
id = "Enter target"
name = "Enter target"
length = "Enter target"

["experiment_step_set.experiment_step.result.category"]
id = "Enter target"
name = "Enter target"
category = "Enter target"

["experiment_step_set.template.infrastructure.sample_reference_set.sample_reference"]
id = "Enter target"
sample_id = "Enter target"
role = "Enter target"
sample_purpose = "Enter target"

["experiment_step_set.template.infrastructure.sample_reference_set.sample_inheritance"]
id = "Enter target"
role = "Enter target"
sample_purpose = "Enter target"

["experiment_step_set.template.infrastructure.parent_data_point_reference_set.parent_data_point_reference"]
id = "Enter target"
series_id = "Enter target"

["experiment_step_set.template.infrastructure.experiment_data_reference_set.experiment_data_reference"]
id = "Enter target"
role = "Enter target"
data_purpose = "Enter target"
experiment_step_id = "Enter target"

["experiment_step_set.template.infrastructure.experiment_data_reference_set.experiment_data_bulk_reference"]
id = "Enter target"
role = "Enter target"
data_purpose = "Enter target"
experiment_step_id_prefix = "Enter target"

["experiment_step_set.template.result.series_set"]
id = "Enter target"
name = "Enter target"
length = "Enter target"

["experiment_step_set.template.result.category"]
id = "Enter target"
name = "Enter target"
category = "Enter target"

["experiment_step_set.experiment_step.method.category.parameter"]
id = "Enter target"
name = "Enter target"
parameter_type = "Enter target"
value = "Enter target"

["experiment_step_set.experiment_step.method.category.series_set"]
id = "Enter target"
name = "Enter target"
length = "Enter target"

["experiment_step_set.experiment_step.result.series_set.series"]
id = "Enter target"
name = "Enter target"
dependency = "Enter target"
series_id = "Enter target"
series_type = "Enter target"
visible = "Enter target"
plot_scale = "Enter target"
value_set = "Enter target"

["experiment_step_set.template.method.category.parameter"]
id = "Enter target"
name = "Enter target"
parameter_type = "Enter target"
value = "Enter target"

["experiment_step_set.template.method.category.series_set"]
id = "Enter target"
name = "Enter target"
length = "Enter target"

["experiment_step_set.template.result.series_set.series"]
id = "Enter target"
name = "Enter target"
dependency = "Enter target"
series_id = "Enter target"
series_type = "Enter target"
visible = "Enter target"
plot_scale = "Enter target"
value_set = "Enter target"

["sample_set.sample.category.parameter.unit"]
id = "Enter target"
factor = "Enter target"
exponent = "Enter target"
offset = "Enter target"

["sample_set.sample.category.series_set.series"]
id = "Enter target"
name = "Enter target"
dependency = "Enter target"
series_id = "Enter target"
series_type = "Enter target"
visible = "Enter target"
plot_scale = "Enter target"
value_set = "Enter target"

["experiment_step_set.experiment_step.infrastructure.parent_data_point_reference_set.parent_data_point_reference.start_value"]
id = "Enter target"
value = "Enter target"

["experiment_step_set.experiment_step.infrastructure.parent_data_point_reference_set.parent_data_point_reference.end_value"]
id = "Enter target"
value = "Enter target"

["experiment_step_set.experiment_step.result.category.parameter"]
id = "Enter target"
name = "Enter target"
parameter_type = "Enter target"
value = "Enter target"

["experiment_step_set.experiment_step.result.category.series_set"]
id = "Enter target"
name = "Enter target"
length = "Enter target"

["experiment_step_set.template.infrastructure.parent_data_point_reference_set.parent_data_point_reference.start_value"]
id = "Enter target"
value = "Enter target"

["experiment_step_set.template.infrastructure.parent_data_point_reference_set.parent_data_point_reference.end_value"]
id = "Enter target"
value = "Enter target"

["experiment_step_set.template.result.category.parameter"]
id = "Enter target"
name = "Enter target"
parameter_type = "Enter target"
value = "Enter target"

["experiment_step_set.template.result.category.series_set"]
id = "Enter target"
name = "Enter target"
length = "Enter target"

["experiment_step_set.experiment_step.method.category.parameter.unit"]
id = "Enter target"
factor = "Enter target"
exponent = "Enter target"
offset = "Enter target"

["experiment_step_set.experiment_step.method.category.series_set.series"]
id = "Enter target"
name = "Enter target"
dependency = "Enter target"
series_id = "Enter target"
series_type = "Enter target"
visible = "Enter target"
plot_scale = "Enter target"
value_set = "Enter target"

["experiment_step_set.experiment_step.result.series_set.series.unit"]
id = "Enter target"
label = "Enter target"
quantity = "Enter target"

["experiment_step_set.template.method.category.parameter.unit"]
id = "Enter target"
factor = "Enter target"
exponent = "Enter target"
offset = "Enter target"

["experiment_step_set.template.method.category.series_set.series"]
id = "Enter target"
name = "Enter target"
dependency = "Enter target"
series_id = "Enter target"
series_type = "Enter target"
visible = "Enter target"
plot_scale = "Enter target"
value_set = "Enter target"

["experiment_step_set.template.result.series_set.series.unit"]
id = "Enter target"
label = "Enter target"
quantity = "Enter target"

["sample_set.sample.category.series_set.series.unit"]
id = "Enter target"
label = "Enter target"
quantity = "Enter target"

["experiment_step_set.experiment_step.result.series_set.series.unit.si_unit"]
id = "Enter target"
factor = "Enter target"
exponent = "Enter target"
offset = "Enter target"

["experiment_step_set.experiment_step.result.category.parameter.unit"]
id = "Enter target"
factor = "Enter target"
exponent = "Enter target"
offset = "Enter target"

["experiment_step_set.experiment_step.result.category.series_set.series"]
id = "Enter target"
name = "Enter target"
dependency = "Enter target"
series_id = "Enter target"
series_type = "Enter target"
visible = "Enter target"
plot_scale = "Enter target"
value_set = "Enter target"

["experiment_step_set.template.result.series_set.series.unit.si_unit"]
id = "Enter target"
factor = "Enter target"
exponent = "Enter target"
offset = "Enter target"

["experiment_step_set.template.result.category.parameter.unit"]
id = "Enter target"
factor = "Enter target"
exponent = "Enter target"
offset = "Enter target"

["experiment_step_set.template.result.category.series_set.series"]
id = "Enter target"
name = "Enter target"
dependency = "Enter target"
series_id = "Enter target"
series_type = "Enter target"
visible = "Enter target"
plot_scale = "Enter target"
value_set = "Enter target"

["sample_set.sample.category.series_set.series.unit.si_unit"]
id = "Enter target"
factor = "Enter target"
exponent = "Enter target"
offset = "Enter target"

["experiment_step_set.experiment_step.method.category.series_set.series.unit"]
id = "Enter target"
label = "Enter target"
quantity = "Enter target"

["experiment_step_set.template.method.category.series_set.series.unit"]
id = "Enter target"
label = "Enter target"
quantity = "Enter target"

["experiment_step_set.experiment_step.method.category.series_set.series.unit.si_unit"]
id = "Enter target"
factor = "Enter target"
exponent = "Enter target"
offset = "Enter target"

["experiment_step_set.experiment_step.result.category.series_set.series.unit"]
id = "Enter target"
label = "Enter target"
quantity = "Enter target"

["experiment_step_set.template.method.category.series_set.series.unit.si_unit"]
id = "Enter target"
factor = "Enter target"
exponent = "Enter target"
offset = "Enter target"

["experiment_step_set.template.result.category.series_set.series.unit"]
id = "Enter target"
label = "Enter target"
quantity = "Enter target"

["experiment_step_set.experiment_step.result.category.series_set.series.unit.si_unit"]
id = "Enter target"
factor = "Enter target"
exponent = "Enter target"
offset = "Enter target"

["experiment_step_set.template.result.category.series_set.series.unit.si_unit"]
id = "Enter target"
factor = "Enter target"
exponent = "Enter target"
offset = "Enter target"
